//
//  LandingInteractor.swift
//  altranassessment
//
//  Created by Marcos Molero on 23/6/18.
//  Copyright (c) 2018 Marcos Molero. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates

protocol LandingBusinessLogic {
    func getGnomes(request: LandingScene.GetGnomes.Request)
}

protocol LandingDataStore {
    var gnomes: [Gnome]? {get set}
}

class LandingInteractor: LandingBusinessLogic, LandingDataStore {
    
    var presenter: LandingPresentationLogic?
    var gnomeStoreWorker: GnomeStoreWorker!
    var gnomes: [Gnome]?
    
    // MARK: Business logic
    func getGnomes(request: LandingScene.GetGnomes.Request) {
        gnomeStoreWorker.getGnomes { (result) in
            switch result {
            case .success(let gnomes):
                self.gnomes = gnomes
                let response = LandingScene.GetGnomes.Response()
                self.presenter?.presentSuccess(response: response)
                break
            case .failure(let error):
                debugPrint(error.localizedDescription)
                let response = LandingScene.GetGnomes.Response()
                self.presenter?.presentFailure(response: response)
                break
            }
        }
    }

}
