//
//  LandingModels.swift
//  altranassessment
//
//  Created by Marcos Molero on 23/6/18.
//  Copyright (c) 2018 Marcos Molero. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates

enum LandingScene {
    struct GetGnomes {
        
        struct Request {
            
        }
        
        struct Response {
            
        }
        
        struct ViewModel {

        }
    }
}
