//
//  LandingPresenter.swift
//  altranassessment
//
//  Created by Marcos Molero on 23/6/18.
//  Copyright (c) 2018 Marcos Molero. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates

protocol LandingPresentationLogic {
    func presentSuccess(response: LandingScene.GetGnomes.Response)
    func presentFailure(response: LandingScene.GetGnomes.Response)
}

class LandingPresenter: LandingPresentationLogic {
    
    weak var viewController: LandingDisplayLogic?
    
    // MARK: Presentation logic
    func presentSuccess(response: LandingScene.GetGnomes.Response) {
        let viewModel = LandingScene.GetGnomes.ViewModel()
        viewController?.displaySuccess(viewModel: viewModel)
    }
    
    func presentFailure(response: LandingScene.GetGnomes.Response) {
        let viewModel = LandingScene.GetGnomes.ViewModel()
        viewController?.displayFailure(viewModel: viewModel)
    }
}
