//
//  GnomeStore.swift
//  altranassessment
//
//  Created by Marcos Molero on 28/09/2018.
//  Copyright (c) 2018 Marcos Molero. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates

protocol GnomeStore {
    func getGnomes(completion: @escaping GnomeStoreGetGnomesCompletionHandler)
}

typealias GnomeStoreGetGnomesCompletionHandler = (GnomeStoreResult<[Gnome]>) -> Void

enum GnomeStoreResult<U> {
    case success(result: U)
    case failure(error: GnomeStoreError)
}

enum GnomeStoreEmptyResult {
    case success
    case failure(error: GnomeStoreError)
}

enum GnomeStoreError: Equatable, Error {
    case cannotGet(String)
}

func ==(lhs: GnomeStoreError, rhs: GnomeStoreError) -> Bool {
    switch (lhs, rhs) {
    case (.cannotGet(let a), .cannotGet(let b)) where a == b: return true
    default:
        return false
    }
}
