//
//  GnomesDependencyInjector.swift
//  altranassessment
//
//  Created by Marcos Molero on 30/09/2018.
//  Copyright (c) 2018 Marcos Molero. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates

import UIKit
import Swinject

// MARK: Inject all scene dependencies

class GnomesDependencyInjector: SwinjectViewControllerDependencyInjector<GnomesViewController> {
    
    // MARK: Registration
    
    override class func registerDependencies(container: Container) {
        container.register(GnomesViewController.self) { (resolver, viewController:GnomesViewController) -> GnomesViewController in
            let interactor = resolver.resolve(GnomesInteractor.self)!
            let presenter = GnomesPresenter()
            let router = GnomesRouter()
            viewController.interactor = interactor
            viewController.router = router
            interactor.presenter = presenter
            presenter.viewController = viewController
            router.viewController = viewController
            router.dataStore = interactor
            return viewController
        }
    }
}
