//
//  GnomesRouter.swift
//  altranassessment
//
//  Created by Marcos Molero on 30/09/2018.
//  Copyright (c) 2018 Marcos Molero. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates

import UIKit

protocol GnomesRoutingLogic {
    func routeToGnome()
}

protocol GnomesDataPassing {
    func passDataToNextScene(for segue:UIStoryboardSegue)
    var dataStore: GnomesDataStore? { get }
}

class GnomesRouter: GnomesRoutingLogic, GnomesDataPassing {
    
    weak var viewController: GnomesViewController?
    var dataStore: GnomesDataStore?
    
    struct SegueIdentifiers {
        static let showGnome = "showGnome"
    }
    
    // MARK: Navigation
    func routeToGnome() {
        viewController?.performSegue(withIdentifier: SegueIdentifiers.showGnome, sender: nil)
    }
    
    // MARK: Communication
    func passDataToNextScene(for segue: UIStoryboardSegue) {
        // NOTE: Teach the router which scenes it can communicate with
        guard let segueIndentifier = segue.identifier else {
            return
        }
        
        switch segueIndentifier {
        case SegueIdentifiers.showGnome:
            passDataToGnomeScene(for: segue)
        default:
            return
        }
    }
    
    func passDataToGnomeScene(for segue: UIStoryboardSegue) {
        if let gnomeViewController = segue.destination as? GnomeViewController {
            var destinationDataStore = gnomeViewController.router?.dataStore
            destinationDataStore?.gnomes = dataStore?.gnomes
            destinationDataStore?.id = dataStore?.id
        }
    }
}
