//
//  GnomesModels.swift
//  altranassessment
//
//  Created by Marcos Molero on 30/09/2018.
//  Copyright (c) 2018 Marcos Molero. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates

enum GnomesScene {
    
    struct GetGnomesFromDataStore {
        
        struct Request {
            
        }
        
        struct Response {
            let gnomes: [Gnome]
        }
        
        struct ViewModel {
            let displayGnomes: [DisplayGnomes]
        }
        
        struct DisplayGnomes {
            let id: Int
            let name: String
            let thumbnail: String
        }
    }
    
    struct SaveGnomeID {
        struct Request {
            let id: Int
        }
        
        struct Response {
            
        }
        
        struct ViewModel {
            
        }
    }
    
}
