//
//  GnomeDependencyInjector.swift
//  altranassessment
//
//  Created by Marcos Molero on 30/09/2018.
//  Copyright (c) 2018 Marcos Molero. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates

import UIKit
import Swinject

// MARK: Inject all scene dependencies

class GnomeDependencyInjector: SwinjectViewControllerDependencyInjector<GnomeViewController> {
    
    // MARK: Registration
    
    override class func registerDependencies(container: Container) {
        container.register(GnomeViewController.self) { (resolver, viewController:GnomeViewController) -> GnomeViewController in
            let interactor = resolver.resolve(GnomeInteractor.self)!
            let presenter = GnomePresenter()
            let router = GnomeRouter()
            viewController.interactor = interactor
            viewController.router = router
            interactor.presenter = presenter
            presenter.viewController = viewController
            router.viewController = viewController
            router.dataStore = interactor
            return viewController
        }
    }
}
