//
//  GnomePresenter.swift
//  altranassessment
//
//  Created by Marcos Molero on 30/09/2018.
//  Copyright (c) 2018 Marcos Molero. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates

protocol GnomePresentationLogic {
    func presentGnome(response: GnomeScene.GetGnome.Response)
}

class GnomePresenter: GnomePresentationLogic {
    
    weak var viewController: GnomeDisplayLogic?
    
    // MARK: Presentation logic
    func presentGnome(response: GnomeScene.GetGnome.Response) {
        let viewModel = mapResponseToViewModel(response: response)
        viewController?.displayGnome(viewModel: viewModel)
    }
    
    func mapResponseToViewModel(response: GnomeScene.GetGnome.Response) -> GnomeScene.GetGnome.ViewModel {
        let displayGnome = mapGnomeToDisplayGnome(gnome: response.gnome)
        let displayFriends = mapGnomeFriendsToDisplayFriends(gnome: response.gnome, gnomes: response.gnomes)
        
        return GnomeScene.GetGnome.ViewModel(displayGnome: displayGnome!, displayFriends: displayFriends)
    }
    
    func mapGnomeToDisplayGnome(gnome: Gnome) -> GnomeScene.GetGnome.DisplayGnome? {
        
        if let name = gnome.name, let thumbnail = gnome.thumbnail, let age = gnome.age, let weight = gnome.weight, let height = gnome.height, let hairColor = gnome.hairColor, let professions = gnome.professions, let friends = gnome.friends {
            
            return GnomeScene.GetGnome.DisplayGnome(id: gnome.id, name: name, thumbnail: thumbnail, age: age, weight: weight, height: height, hairColor: hairColor, professions: professions, friends: friends)
        }
        return nil
    }
    
    func mapGnomeFriendsToDisplayFriends(gnome: Gnome, gnomes: [Gnome]) -> [GnomeScene.GetGnome.DisplayFriend] {
        var displayFriends: [GnomeScene.GetGnome.DisplayFriend] = []
        
        if let friends = gnome.friends {
            for friendName in friends {
                for gnome in gnomes {
                    if friendName == gnome.name {
                        let displayFriend = GnomeScene.GetGnome.DisplayFriend(id: gnome.id, name: (gnome.name)!, thumbnail: (gnome.thumbnail)!)
                        displayFriends.append(displayFriend)
                    }
                }
            }
        }
        
        return displayFriends
    }
}
