//
//  GnomeRouter.swift
//  altranassessment
//
//  Created by Marcos Molero on 30/09/2018.
//  Copyright (c) 2018 Marcos Molero. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates

import UIKit

protocol GnomeRoutingLogic {
    
}

protocol GnomeDataPassing {
    func passDataToNextScene(for segue:UIStoryboardSegue)
    var dataStore: GnomeDataStore? { get }
}

class GnomeRouter: GnomeRoutingLogic, GnomeDataPassing {
    
    weak var viewController: GnomeViewController?
    var dataStore: GnomeDataStore?
    
    // MARK: Navigation
    
    // MARK: Communication
    
    func passDataToNextScene(for segue: UIStoryboardSegue) {
        // NOTE: Teach the router which scenes it can communicate with
        
    }
}
