//
//  GnomeInteractor.swift
//  altranassessment
//
//  Created by Marcos Molero on 30/09/2018.
//  Copyright (c) 2018 Marcos Molero. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates

protocol GnomeBusinessLogic {
    func getGnome(request: GnomeScene.GetGnome.Request)
}

protocol GnomeDataStore {
    var gnomes: [Gnome]? {get set}
    var id: Int? {get set}
}

class GnomeInteractor: GnomeBusinessLogic, GnomeDataStore {
    
    var presenter: GnomePresentationLogic?
    var gnomes: [Gnome]?
    var id: Int?
    
    // MARK: Business logic
    func getGnome(request: GnomeScene.GetGnome.Request) {
        
        for gnome in gnomes! {
            if gnome.id == id {
                let response = GnomeScene.GetGnome.Response(gnome: gnome, gnomes: gnomes!)
                presenter?.presentGnome(response: response)
            }
        }
    }

}
